on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        sed --in-place '/<addon/ s/version="[^"]*"/version="'${GITHUB_SHA::7}'"/' addon.xml
        mkdir -p /tmp/plugin.video.stash
        rsync -a --exclude 'resources/stash_logo.svg' addon.xml addon.py resources /tmp/plugin.video.stash
      - uses: actions/upload-artifact@v3
        with:
          name: plugin.video.stash.${GITHUB_SHA::7}
          path: /tmp/plugin.video.stash
